name: 'Code Quality Check'
description: 'Run Biome code quality checks'

runs:
  using: 'composite'
  steps:
    - name: Setup Biome
      uses: biomejs/setup-biome@v2
      with:
        version: latest
    - name: Run Biome
      shell: bash
      run: biome ci .
